import Footer from "@/components/sections/landing-page/footer/footer";
import HeaderNavbarPublic from "@/components/sections/landing-page/header/navbar-public";


const PolicyPage = () => {
  return (
<><HeaderNavbarPublic/>
    <div className="max-w-4xl mx-auto px-4 py-8 text-muted-foreground my-26">
      <h1 className="text-3xl font-bold text-secondary-foreground mb-2">Privacy Policy</h1>
      <p className="text-sm text-secondary mb-6">Last updated: July 19, 2025</p>
      
      <div className="space-y-6">
        <section>
          <p className="mb-4">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p>
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.privacypolicies.com/privacy-policy-generator/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Privacy Policy Generator</a>.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-secondary-foreground mb-4">Interpretation and Definitions</h2>
          
          <h3 className="text-xl font-medium text-secondary-foreground mb-2">Interpretation</h3>
          <p className="mb-4">
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          
          <h3 className="text-xl font-medium text-secondary-foreground mb-2">Definitions</h3>
          <p className="mb-4">For the purposes of this Privacy Policy:</p>
          
          <ul className="space-y-3 pl-5 list-disc">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to VoteBuddy.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: Philippines</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong>Website</strong> refers to VoteBuddy, accessible from <a href="votebuddy.cc" rel="external nofollow noopener" target="_blank" className="text-primary hover:underline">votebuddy.cc</a></li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-secondary-foreground mb-4">Collecting and Using Your Personal Data</h2>
          
          <h3 className="text-xl font-medium text-secondary-foreground mb-2">Types of Data Collected</h3>
          
          <h4 className="text-lg font-medium text-secondary-foreground mb-2">Personal Data</h4>
          <p className="mb-4">
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="space-y-2 pl-5 list-disc mb-4">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Usage Data</li>
          </ul>
          
          <h4 className="text-lg font-medium text-secondary-foreground mb-2">Usage Data</h4>
          <p className="mb-4">
            Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device&aposs Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          
          <h4 className="text-lg font-medium text-secondary-foreground mb-2">Tracking Technologies and Cookies</h4>
          <p className="mb-4">
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
          </p>
          
          <div className="bg-gray-50 p-4 rounded-lg mb-4">
            <p className="mb-2">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
          </div>
        </section>

        {/* Continue with other sections following the same pattern */}

        <section>
          <h2 className="text-2xl font-semibold text-secondary-foreground mb-4">Contact Us</h2>
          <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className="space-y-2 pl-5 list-disc">
            <li>By email: <a href="mailto:evanfeliza22@gmail.com" className="text-primary hover:underline">evanfeliza22@gmail.com</a></li>
            <li>By visiting this page on our website: <a href="https://www.votebuddy.cc/" rel="external nofollow noopener" target="_blank" className="text-primary hover:underline">https://www.votebuddy.cc/</a></li>
          </ul>
        </section>
      </div>
    </div>
    <Footer/></>
  );
}

export default PolicyPage;
