import type { Metadata } from "next"
import { Toaster } from "react-hot-toast"
import { Provider as SessionProvider } from "../lib/providers/session-provider"
import "./globals.css"


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
          className={`antialiased`}
            >
                <SessionProvider>{children}</SessionProvider>
                <Toaster
                    position="top-center"
                    reverseOrder={false}
                    gutter={8}
                />
            </body>
        </html>
    )
}
