import '@schedule-x/theme-default/dist/index.css'
import type { Metadata } from "next"
import { Toaster } from "react-hot-toast"
import "./globals.css"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
          className={`antialiased font-poppins`}
            >
          {children}
                <Toaster
                    position="top-center"
                    reverseOrder={false}
                    gutter={8}
                />
            </body>
        </html>
    )
}
